version: '3.8'

services:
  tag-suggestor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: 